export const cuisineOptions = [
    { value: 'African', label: 'African', color: '#00B8D9' },
    { value: 'American', label: 'American', color: '#0052CC' },
    { value: 'British', label: 'British', color: '#5243AA' },
    { value: 'Cajun', label: 'Cajun', color: '#FF5630' },
    { value: 'Carribean', label: 'Carrieban', color: '#FF8B00' },
    { value: 'Chinese', label: 'Chinese', color: '#FFC400' },
    { value: 'Eastern European', label: 'Eastern European', color: '#36B37E' },
    { value: 'European', label: 'European', color: '#00875A' },
    { value: 'French', label: 'French', color: '#253858' },
    { value: 'German', label: 'German', color: '#666666' },
    { value: 'Greek', label: 'Greek', color: '#00B8D9' },
    { value: 'Indian', label: 'Indian', color: '#0052CC' },
    { value: 'Irish', label: 'Irish', color: '#5243AA' },
    { value: 'Italian', label: 'Italian', color: '#FF5630' },
    { value: 'Japanese', label: 'Japanese', color: '#FF8B00' },
    { value: 'Jewish', label: 'Jewish', color: '#FFC400' },
    { value: 'Korean', label: 'Korean', color: '#36B37E' },
    { value: 'Latin American', label: 'Latin American', color: '#00875A' },
    { value: 'Mediterranean', label: 'Mediterranean', color: '#253858' },
    { value: 'Mexican', label: 'Mexican', color: '#666666' },
    { value: 'Middle Eastern', label: 'Middle Eastern', color: '#36B37E' },
    { value: 'Nordic', label: 'Nordic', color: '#00875A' },
    { value: 'Southern', label: 'Southern', color: '#253858' },
    { value: 'Spanish', label: 'Spanish', color: '#666666' },
    { value: 'Thai', label: 'Thai', color: '#00B8D9' },
    { value: 'Vietnamese', label: 'Vietnamese', color: '#0052CC' }
  ];

export const dietaryOptions = [
    { value: 'gluten free', label: 'Gluten Free', color: '#00B8D9' },
    { value: 'ketogenic', label: 'Ketogenic', color: '#0052CC' },
    { value: 'Vegetarian', label: 'vegetarian', color: '#5243AA' },
    { value: 'Lacto-Vegetarian', label: 'lacto-vegetarian', color: '#FF5630' },
    { value: 'Ovo-Vegetarian', label: 'ovo-vegetarian', color: '#FF8B00' },
    { value: 'Vegan', label: 'vegan', color: '#FFC400' },
    { value: 'Pescetarian', label: 'perscetarian', color: '#36B37E' },
    { value: 'Paleo', label: 'paleo', color: '#00875A' },
    { value: 'Primal', label: 'primal', color: '#253858' },
    { value: 'Whole30', label: 'whole30', color: '#666666' },
];